#!/usr/bin/python
import sys
import subprocess
import time
import glob
from time import strftime,localtime
if (len(sys.argv) < 2):
   print("Parameter 1 - Iris instance name, parameter 2 - Iris namespace")
   sys.exit(1)

if (sys.argv[1]==""):
   print("Enter IRIS instance name as the first parameter")
   sys.exit(1)

if (sys.argv[2]==""):
   print("Enter the IRIS namespace as the second parameter")
   sys.exit(0)
f = open("/var/log/nagios/nagios.log", "r")
for lne in f:
   proc=0
   if "CURRENT SERVICE STATE" in lne:
      proc=1 
      bits=lne.split(";")
      bits1=bits[0].split(" ")
      strdat=bits1[0].replace("[","")
      strdat=strdat.replace("]","")
      objscr=["iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"date\")=\"" + strftime("%c",localtime(float(strdat))) + "\"'"]
      objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"Status\")=\"" + bits[2] + "\"'")
      objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"Check\")=\"" + bits[3] + "\"'")
      objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"Info\")=\"" + bits[5] + "\"'")
   elif "CURRENT HOST STATE" in lne:
      proc=1
      bits=lne.split(";")
      bits1=bits[0].split(" ")
      strdat=bits1[0].replace("[","")
      strdat=strdat.replace("]","")
      objscr=["iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"date\")=\"" + strftime("%c",localtime(float(strdat))) + "\"'"]
      objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"Status\")=\"" + bits[1] + "\"'")
      objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"Check\")=\"" + bits[2] + "\"'")
      objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"Info\")=\"" + bits[4] + "\"'")

   if (proc==1):
      for cmd in objscr:
         print(cmd)
         #
         # Now run the objectscript with iriscmd
         #
         process = subprocess.Popen(cmd,
                  stdout=subprocess.PIPE,
                  stderr=subprocess.PIPE,
                  shell=True)
         resp = process.communicate()
         if (resp[1] != ""):
            print("There was an ERROR when running - " + cmd)
            sys.exit(1)
         else:
            print(cmd + " - run SUCCESSFULLY")
if (len(sys.argv) == 4):
   if (sys.argv[3] == "full"):
     print("Now Running import of archives")
     time.sleep(5)
     path = "/var/log/nagios/archives/*.log"
     for filename in glob.glob(path):
           with open(filename, 'r') as f:
              for lne in f:
                 proc=0
                 if "CURRENT SERVICE STATE" in lne:
                    proc=1
                    bits=lne.split(";")
                    bits1=bits[0].split(" ")
                    strdat=bits1[0].replace("[","")
                    strdat=strdat.replace("]","")
                    objscr=["iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"date\")=\"" + strftime("%c",localtime(float(strdat))) + "\"'"]
                    objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"Status\")=\"" + bits[2] + "\"'")
                    objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"Check\")=\"" + bits[3] + "\"'")
                    objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + bits[1] + "\",\"" + strdat + "\",\"Info\")=\"" + bits[5] + "\"'")
                 elif "CURRENT HOST STATE" in lne:
                    proc=1
                    bits=lne.split(";")
                    bits1=bits[0].split(" ")
                    strdat=bits1[0].replace("[","")
                    strdat=strdat.replace("]","")
                    objscr=["iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"date\")=\"" + strftime("%c",localtime(float(strdat))) + "\"'"]
                    objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"Status\")=\"" + bits[1] + "\"'")
                    objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"Check\")=\"" + bits[2] + "\"'")
                    objscr.append("iriscmd '" + sys.argv[1] + "' '" + sys.argv[2] + "' 'S ^NAGIOS(\"" + bits1[4] + "\",\"" + "hostchk" + "\",\"" + strdat + "\",\"Info\")=\"" + bits[4] + "\"'")

                 if (proc==1):
                    for cmd in objscr:
                       print(cmd)
                       #
                       # Now run the objectscript with iriscmd
                       #
                       process = subprocess.Popen(cmd,
                              stdout=subprocess.PIPE,
                              stderr=subprocess.PIPE,
                              shell=True)
                       resp = process.communicate()
                       if (resp[1] != ""):
                          print("There was an ERROR when running - " + cmd)
                          sys.exit(1)
                       else:
                          print(cmd + " - run SUCCESSFULLY")
